import './js/trending';
import './js/headerSearch';
import './js/api-common';
import './js/modal';
import './js/modalTeamForm';
import './js/scrollTo';
import './js/burger-menu';
import './js/popup';
import './js/firebase';
// import './js/switcher';
