import './js/api-common';
import './js/trending';
import './js/api-genres.js';
import './js/headerSearch';
import './js/modal';
import './js/modalTeamForm';
import './js/scrollTo';
import './js/sortGenres';
import './js/popup';
import './js/firebase';
import './js/theme';
import './js/trailers';
// import './js/libraryButtonSwitch';